package com.sunmi.tapro.taplink.sdk.model.base

import com.google.gson.JsonObject
import com.google.gson.annotations.SerializedName

/**
 * Taplink basic request parameters
 *
 * All requests use this structure
 * Contains common fields: appSign, version, timeStamp, action, bizData, traceId
 *
 * @author TaPro Team
 * @since 2025-01-XX
 */
data class BasicRequest(
    /**
     * Message signature, generated using HMAC-SHA256 algorithm
     * Required
     */
    @SerializedName("appSign")
    val appSign: String,
    
    /**
     * SDK version number, format: x.y.z
     * Required
     */
    @SerializedName("version")
    val version: String,
    
    /**
     * Request timestamp, format: yyyyMMddHHmmssSSS
     * Required
     */
    @SerializedName("timeStamp")
    val timeStamp: String,
    
    /**
     * Operation type identifier
     * Required
     */
    @SerializedName("action")
    val action: String,
    
    /**
     * Business data, varies based on action type
     * Required, *Request type is the content of bizData
     */
    @SerializedName("bizData")
    val bizData: JsonObject,
    
    /**
     * Trace ID, used to track concurrent requests, ensures response returns to corresponding callback
     * Required, automatically generated by system
     */
    @SerializedName("traceId")
    val traceId: String
)












